---
title: "P8105_HW2_bjl2150"
author: "Briana Lettsome"
date: "September 27, 2018"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
```

## Problem 1

```{r}
## Reading in the NYC transit csv file plus cleaning the data

nyc_transit = read_csv(file = "./data/NYC_Transit_Subway_Entrance_And_Exit_Data.csv") %>%
  janitor::clean_names()

## Removing the not requested variables
  
nyc_transit_clean = select(nyc_transit, -exit_only, -staffing, -staff_hours, -ada_notes, 
                           -free_crossover, -north_south_street, -east_west_street, 
                           -corner, -entrance_latitude, -entrance_longitude, 
                           -station_location, -entrance_location)%>%
      mutate(entry = recode(entry, YES = TRUE, NO = FALSE))

## Obtaining the dimension (rows X columns) of the datafile NYC_Transit_clean

dim(nyc_transit_clean)
```
Paragraph

```{r}
## Question 1: Distinct function

 distinct(nyc_transit_clean, station_name, line)
```
 
There are 465 distinct stations.

```{r}
## Question 2: ADA compliance

filter(nyc_transit_clean, ada == TRUE) %>%
distinct(station_name, line, ada = TRUE)
```
There are 84 stations that are ADA compliant.

```{r}
## Question 3: Proportion




filter(nyc_transit_clean, vending == "NO") %>%
nrow()

filter(nyc_transit_clean, entry == "TRUE", vending == "NO") %>%
nrow()
```

```{r}
## Gathering route columns to make a tidier dataset

nyc_transit_tidy =
  gather(nyc_transit_clean, key = "route_number", value = "route_name", route1:route11) 

## Determining distinct stations that serve A train

filter(nyc_transit_tidy, route_name == "A") %>%
distinct(station_name, line, route_name = "A")
```

There are 60 distinct stations that served the A train.

```{r}
## Determining ADA compliance

filter(nyc_transit_tidy, ada == TRUE) %>%
distinct(station_name, line, ada = TRUE)
```
There are 84 distinct stations that are ADA compliant.


## Problem 2


```{r}
## Part 2 A

library(readxl)

## Importing and cleaning Mr. Trash Wheel excel file

trash_wheel = read_excel("./data/HealthyHarborWaterWheelTotals2018-7-28.xlsx", 
              sheet = "Mr. Trash Wheel")


trash_wheel = read_excel("./data/HealthyHarborWaterWheelTotals2018-7-28.xlsx", 
              sheet = "Mr. Trash Wheel", range = "A2:N336") %>% 
              janitor::clean_names() %>% 
              filter(dumpster != "N/A") %>% 
mutate(sports_balls = as.integer(sports_balls)) 
```

```{r}
## Part 2B

## Reading in Trash Wheel, selecting in sheet "2016 Precipiation, and cleaning"

precip_16 = read_excel("./data/HealthyHarborWaterWheelTotals2018-7-28.xlsx", 
              sheet = "2016 Precipitation", range = "A2:B14") %>%
 janitor::clean_names() %>%
  mutate(year = 2016)


precip_17 = read_excel("./data/HealthyHarborWaterWheelTotals2018-7-28.xlsx", 
              sheet = "2017 Precipitation", range = "A2:B14") %>%
 janitor::clean_names() %>%
  mutate(year = 2017)

precipitation = bind_rows(precip_16, precip_17) %>%
   mutate(month = month.name[month])
```

```{r}

```

## Problem 3

```{r}
# install.packages("devtools")
devtools::install_github("p8105/p8105.datasets")

library(p8105.datasets)

data(brfss_smart2010) %>% 
  janitor::clean_names()



```